services:
  zaalima-postgres:
    image: postgres:16-alpine
    container_name: zaalima-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: iam_user
      POSTGRES_PASSWORD: iam_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iam_user -d iam_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  zaalima-redis:
    image: redis:7-alpine
    container_name: zaalima-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zaalima-iam-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zaalima-iam-server
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://zaalima-postgres:5432/iam_db
      SPRING_DATASOURCE_USERNAME: iam_user
      SPRING_DATASOURCE_PASSWORD: iam_password
      SPRING_DATA_REDIS_HOST: zaalima-redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      zaalima-postgres:
        condition: service_healthy
      zaalima-redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: