spring:
  application:
    name: iam-server

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zaalima_iam
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085
